### ISSUE TITLE
Parameters not found

### ISSUE THREAD

**Issue by jermwormza** [microsoft/cross-tenant#10]
Hi There,

I'm probably missing a prerequisite but I'm getting parameter not found issues on both sides:
Target: MailboxMoveCapability, RemoteTenant
Resource: MailboxMoveCapability, OAuthApplicationId

It seems the version of Set/New OrganizationRelationship I have does not have these parameters - how do I update this?

p.s. Sorry If I'm posting this in the wrong place not sure where else to go.

**Comment by ropow** [comment]
> Hi There,
> 
> I'm probably missing a prerequisite but I'm getting parameter not found issues on both sides:
> Target: MailboxMoveCapability, RemoteTenant
> Resource: MailboxMoveCapability, OAuthApplicationId
> 
> It seems the version of Set/New OrganizationRelationship I have does not have these parameters - how do I update this?
> 
> p.s. Sorry If I'm posting this in the wrong place not sure where else to go.

At this time we are looking into this.

**Comment by jermwormza** [comment]
Hi There.

I had also posted a query on the MS Site where the documentation is hosted, I got a response on that, asking for screenshots of the error, so in order to provide such I just tried again now, the scripts are now working and the New-OrganizationRelationship and the New-MigrationEndpoint now appear to have the new parameters available **but only on my target Tenant**

I had been trying a number of times in the last 2 days otherwise I'd think I was imagining things, perhaps this is due to a delayed rollout to my tenants? Not sure what happened but it is now working on the target but not on the resource.

This is the error:
![Screenshot 2020-09-30 at 07 14 06](https://user-images.githubusercontent.com/20230394/94645735-e015e200-02ec-11eb-9988-9d6b6f225b8e.png)

**Comment by ropow** [comment]
> Hi There.
> 
> I had also posted a query on the MS Site where the documentation is hosted, I got a response on that, asking for screenshots of the error, so in order to provide such I just tried again now, the scripts are now working and the New-OrganizationRelationship and the New-MigrationEndpoint now appear to have the new parameters available **but only on my target Tenant**
> 
> I had been trying a number of times in the last 2 days otherwise I'd think I was imagining things, perhaps this is due to a delayed rollout to my tenants? Not sure what happened but it is now working on the target but not on the resource.
> 
> This is the error:
> ![Screenshot 2020-09-30 at 07 14 06](https://user-images.githubusercontent.com/20230394/94645735-e015e200-02ec-11eb-9988-9d6b6f225b8e.png)

This is currently due to an interim build blocking the parameters. A new build is currently rolling out that will unblock you, once your mailbox is hosted on a server that received it. This should happen within the next week.

**Comment by Nishit92inn** [comment]
I am having the same issue on my source tenant where these attributes are not found however the same script works in my test tenant and target tenant. 

Any help on this  ?

**Comment by ropow** [comment]
Good morning, Nishit.

The scripts here on Github are no longer used in cross-tenant mailbox migration. Please refer to the current documentation for steps on setting up your environments and performing the migration.

https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide

Thanks,

Roman

**Comment by Nishit92inn** [comment]
Hi Roman,

Thanks for your response, i am trying the steps from the article you have provided but i am still getting the same error.

The strange thing is that the script is only not working in the source tenant , it works in the target tenant and a test tenant i have.

No sure if this specific to the tenant but i have raised a support request with Microsoft.

Thanks
Nishit Mishra
________________________________
