### ISSUE TITLE
AppRegistration fail sending Guest Invite

### ISSUE THREAD

**Issue by PrudhommeWTF** [microsoft/cross-tenant#11]
When using the SetupCrossTenantRelationshipForTargetTenant.ps1 script, the AppRegistration is not able to invite Resource Tenant account specified in ResourceTenantAdminEmail. The Azure AD Guest Invitation result in the Error: "Insuficient privileges to perform the requested operation by the application '00000003-0000-0000-c000-000000000000', ControllerName=MSGraphInviteAPI, ActionName=CreateInvite, URL absolute path=/api/GuidOfTheGuestAccountHere/Invites" in line 523

Quick and dirty fix was to:

1. Replace:
`$MS_GRAPH_APP_ROLE = "Directory.ReadWrite.All"`
by:
`$MS_GRAPH_APP_ROLE = 'Directory.ReadWrite.All','User.Invite.All'`
2.  Replace:
```
        $msGraphAppPermission = $msGraphSpn.AppRoles | ? { $_.Value -eq $MS_GRAPH_APP_ROLE }
        $reqGraph = New-Object -TypeName "Microsoft.Open.AzureAD.Model.RequiredResourceAccess"
        $reqGraph.ResourceAppId = $msGraphSpn.AppId
        $reqGraph.ResourceAccess = New-Object -TypeName "Microsoft.Open.AzureAD.Model.ResourceAccess" -ArgumentList $msGraphAppPermission.Id,"Role"
        $appPermissions += $reqGraph

```
by:
```
    $reqGraph = New-Object -TypeName "Microsoft.Open.AzureAD.Model.RequiredResourceAccess"
    $reqGraph.ResourceAppId = $msGraphSpn.AppId
    foreach ($role in $MS_GRAPH_APP_ROLE) {
            $reqGraph.ResourceAccess += New-Object -TypeName "Microsoft.Open.AzureAD.Model.ResourceAccess" -ArgumentList ($msGraphSpn.AppRoles | Where-Object -FilterScript { $_.Value -eq $role }).Id, 'Role'
        }
    }
    $appPermissions += $reqGraph
```
3. Replace:
```
    if ($azAppPermissions.HasFlag([ApplicationPermissions]::MSGraph)) {
        $permissions += "MSGraph - $MS_GRAPH_APP_ROLE. "
    }
```
by:
```
    if ($azAppPermissions.HasFlag([ApplicationPermissions]::MSGraph)) {
        foreach ($role in $MS_GRAPH_APP_ROLE) {
            $permissions += "MSGraph - $role. "
        }
    }
```

Issue solved

**Comment by anshuldube** [comment]
Thanks for reporting this and suggesting the fix. We will take a look at this, however, from documentation it seems like Directory.ReadWrite.All should have been enough for [Invitation API](https://docs.microsoft.com/en-us/graph/api/invitation-post?view=graph-rest-1.0&tabs=http#permissions)

**Comment by PrudhommeWTF** [comment]
You are right. Following your link to the invitation API Doc it should work but apparently [Permissions Reference](https://docs.microsoft.com/en-us/graph/permissions-reference#application-permissions-17) says otherwise
