### ISSUE TITLE
Naming/Documentation Clarity

### ISSUE THREAD

**Issue by flarecriteria** [microsoft/cross-tenant#12]
Both `SetupCrossTenantRelationshipForTargetTenant.ps1` and `SetupCrossTenantRelationshipForResourceTenant.ps1` have the synopsis:

>This script can be used by a tenant that wishes to pull resources out of another tenant.
>For example contoso.com would run this script in order to pull mailboxes from fabrikam.com tenant.

The second line in `SetupCrossTenantRelationshipForResourceTenant.ps1` should be changed.

When reading (https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide) it says:

>-ResourceTenantDomain | Source tenant domain, such as fabrikam.onmicrosoft.com.

but in the synopsis you have

>   SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain contoso.onmicrosoft.com -TargetTenantDomain fabrikam.onmicrosoft.com

It makes it a bit confusing to tell which tenant is which, since the documentation clearly shows in the image the that you're pulling mailboxes from the source tenant, but the examples in the synopsis are reversed.

Finally you in `SetupCrossTenantRelationshipForResourceTenant.ps1` have:
> this script is intended for the resource tenant in above example fabrikam.com

but the example shows `-ResourceTenantDomain contoso.onmicrosoft.com`

Am I just completely misreading something?

**Comment by ropow** [comment]
Fixed issues with readability in the scripts. These should be clear now.
