### ISSUE TITLE
Use filtering for SPN

### ISSUE THREAD

**Issue by anshuldube** [microsoft/cross-tenant#13]
For a large organization that has many SPNs it could cause timeouts for pulling all the SPNs rather we should filter on the SPN lookup itself.

 ## Grab all the SPNs ##
        $spns = Get-AzureADServicePrincipal -All $true
        $exoAppSpn = $spns | ? { $_.AppId -eq $EXO_APP_ID }

This should be: 

`Get-AzureADServicePrincipal -Filter  "AppId eq '$EXO_APP_ID'"`

**Comment by ropow** [comment]
Fixed.
