### ISSUE TITLE
parameter set cannot be resolved

### ISSUE THREAD

**Issue by PavelMarinov87** [microsoft/cross-tenant#17]
Hi, I just ran into an error with the script for the Target Tennant:

SetupCrossTenantRelationshipForTargetTenant.ps1 : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ .\SetupCrossTenantRelationshipForTargetTenant.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [SetupCrossTenan...argetTenant.ps1], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,SetupCrossTenantRelationshipForTargetTenant.ps1

Can somebody help with this?

**Comment by ropow** [comment]
Can you please provide us with the parameters you ran with the script.

Thanks,

Roman
