### ISSUE TITLE
Method invocation failed because [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext] does not contain a method named 'AcquireToken'.

### ISSUE THREAD

**Issue by TCapp99** [microsoft/cross-tenant#21]
During the tenant relationship for target tenant script, the script is failing consistently with the error:

C:\SetupCrossTenantRelationshipForTargetTenant.ps1 : Method invocation
failed because [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext] does not contain a method named
'AcquireToken'.
At line:1 char:1
+ .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDoma ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [SetupCrossTenan...argetTenant.ps1], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound,SetupCrossTenantRelationshipForTargetTenant.ps1

I have been unable to modify the script in any helpful way to bypass this error but with some digging I was finding that the method does not seem to be documented per the docs page (https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext?view=azure-dotnet)

The script is able to complete the Admin consent URI's for both tenants but its failing as soon as the script is continued.

**Comment by ropow** [comment]
Good morning Travis,

Can you download the latest file from the release version, which was just updated with the fix for this issue, and try again.

Thanks,

Roman

**Comment by ropow** [comment]
Travis,

I am closing this issue for now, the latest version of the script should have resolved this issue. Please let us know if it hasn't.

Thanks,

Roman
