### ISSUE TITLE
syntax issue

### ISSUE THREAD

**Issue by akhavdey** [microsoft/cross-tenant#25]
last commit causes syntax issue
`At C:\migration\CrossTenantMailboxMigration\SetupCrossTenantRelationshipForTargetTenant.ps1:541 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken`
removing "}" on line 541 char:1 leads to

`C:\migration\CrossTenantMailboxMigration\SetupCrossTenantRelationshipForTargetTenant.ps1 : Parameter set 
cannot be resolved using the specified named parameters.
At line:1 char:1
+ .\SetupCrossTenantRelationshipForTargetTenant.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [SetupCrossTenan...argetTenant.ps1], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,SetupCrossTenantRelationshipForTargetTenant.ps1
 `

**Comment by ropow** [comment]
Thanks for catching this. This issue has been resolved.

Roman
