### ISSUE TITLE
New-OrganizationRelatioship missing MailboxMoveCapability

### ISSUE THREAD

**Issue by Factorization** [microsoft/cross-tenant#27]
Both of my source and target tenants do not have the MailboxMoveCapability parameter for the New/Set-OrganizationRelationship. Both tenants also are missing the RemoteTenant, ApplicationId and AppSecretKeyVaultUrl parameters for New-MigrationEndpoint. Has the cross-tenant migration been rolled out to all tenants yet? Is there anything I can do to enable this for my tenants?

**Comment by psykokwak4** [comment]
This repository is not meant to track configuration errors,
Please email your source / target tenant information plus errors to crosstenantmigrationpreview@service.microsoft.com.

**Comment by Factorization** [comment]
Thanks for the update. I would recommend adding some try/catch error handling around these sections of code:
![image](https://user-images.githubusercontent.com/10674846/105529722-a4d46000-5c9b-11eb-9d39-c8c1e1afacc2.png)
Specifically lines 548, 557 and 566 should all have some error handling added to those commands.

The output can be very misleading. It says the MigrationEndpoint was created when it did not get created:
![image](https://user-images.githubusercontent.com/10674846/105530808-31cbe900-5c9d-11eb-836e-1b96eb57b479.png)

**Comment by psykokwak4** [comment]
Feel free to open a PR

**Comment by psykokwak4** [comment]
Added try/catch to New-MigrationEndpoint . . .
