### ISSUE TITLE
Getting error of "You cannot call a method on a null-valued expression"

### ISSUE THREAD

**Issue by pgdrews** [microsoft/cross-tenant#32]
I was nearing completing of the Target tenant setup and hit a block.  I got through the consent, and the email was sent to the source tenant admin email.   Then, after it was attempting to finish configuring the exchange side, I get the null error.   See screenshots and appreciate any insights or further troubleshooting.  Thanks!
![crosstenant-screenshot1](https://user-images.githubusercontent.com/7563343/110867406-4df70a00-828c-11eb-86a1-874435faa8ba.png)
![crosstenant-screenshot2](https://user-images.githubusercontent.com/7563343/110867430-56e7db80-828c-11eb-9d0a-d483c03ec24e.png)

here's the script/parameters screenshot
![crosstenant-screenshot3](https://user-images.githubusercontent.com/7563343/110867590-a0d0c180-828c-11eb-9b5f-b0d1499b4f14.png)

**Comment by ropow** [comment]
Patrick,

Can you send everything to crosstenantmigrationpreview@service.microsoft.com without the redaction. Also, have you tried rerunning the script to see if it was a one off issue?

Thanks,

Roman

**Comment by pgdrews** [comment]
Hi Roman - yes, I did run it again, and it doesn't go through the long Exchange setup, but results in the same error the next time.  

I will email the info shortly.  Thanks!

Patrick

**Comment by ropow** [comment]
Thanks Patrick,

Could you also run the verify script included with the release files in the target tenant.

Roman

**Comment by ropow** [comment]
While this error may fire, there is no issue and the script ran successfully.
