### ISSUE TITLE
Missing closing bracket for line 581

### ISSUE THREAD

**Issue by eowend** [microsoft/cross-tenant#33]
When you run the script, you get the following error:
#############################################
At C:\SetupCrossTenantRelationshipForTargetTenant.ps1:581 char:200
+ ... ing]$appId, $appSecretCert, [string]$appReplyUrl, [string]$appName) {
+                                                                         ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndCurlyBrace
##############################################

Adding a closing bracket on line 642 fixes the issue.

**Comment by ropow** [comment]
Thanks for pointing this out! It has been fixed.
