### ISSUE TITLE
The term '=' is not recognized

### ISSUE THREAD

**Issue by jcornwe** [microsoft/cross-tenant#37]
Getting the following error. I am able to get through the login prompt before receiving this error. When I try and run without the "=" in the certificate subject, the script fails to validate. Am I missing something simple?

```
PS C:\Users\jerem\OneDrive - ALICE Training Institute\Powershell> .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain healthec.onmicrosoft.com -ResourceTenantAdminEmail redacted@healthec.com -TargetTenantDomain healthecind.onmicrosoft.com -ResourceTenantId redacted -SubscriptionId redacted -ResourceGroup "Migration" -KeyVaultName "healthecind-vault" -CertificateName "MigrationCert" -CertificateSubject "CN=healthecind" -AzureAppPermissions Exchange, MSGraph 


Welcome to the Cross-tenant mailbox migration preview! Before running this script, please be sure to review the details provided on docs.microsoft.com at the following URL: 
https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration

It is also recommended before running this script to review the script in a script editor or Notepad prior to running. 

For general feedback and / or questions, please contact crosstenantmigrationpreview@service.microsoft.com.
This is not a support alias and should not be used if you are currently experiencing an issue and need immediate assistance. 

Setting up key vault in the healthecind.onmicrosoft.com tenant

Name                                     Account                            SubscriptionName                  Environment                       TenantId                         
----                                     -------                            ----------------                  -----------                       --------                         
Azure subscription 1 (redacted... redacted@HealthECind.onm... Azure subscription 1              AzureCloud                        redacted...
Exchange app given access to KeyVault healthecind-vault
Application healthecind_Friends_healthec_1462 created successfully in healthecind.onmicrosoft.com tenant with following permissions. MSGraph - User.Invite.All. Exchange - Mailbox
.Migration
Admin consent URI for healthecind.onmicrosoft.com tenant admin is -
redacted\SetupCrossTenantRelationshipForTargetTenant.ps1 : The term '=' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDoma ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (=:String) [SetupCrossTenan...argetTenant.ps1], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,SetupCrossTenantRelationshipForTargetTenant.ps1
```

**Comment by ropow** [comment]
Can you try without the "" around CN=healthecind

I believe that is the issue.

Thanks,

Roman

From: jcornwe ***@***.***>
Sent: Monday, March 15, 2021 10:23 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] The term '=' is not recognized (#37)


Getting the following error. I am able to get through the login prompt before receiving this error. When I try and run without the "=" in the certificate subject, the script fails to validate. Am I missing something simple?

`PS C:\Users\jerem\OneDrive - ALICE Training Institute\Powershell> .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain healthec.onmicrosoft.com -ResourceTenantAdminEmail ***@***.******@***.***> -TargetTenantDomain healthecind.onmicrosoft.com -ResourceTenantId redacted -SubscriptionId redacted -ResourceGroup "Migration" -KeyVaultName "healthecind-vault" -CertificateName "MigrationCert" -CertificateSubject "CN=healthecind" -AzureAppPermissions Exchange, MSGraph

Welcome to the Cross-tenant mailbox migration preview! Before running this script, please be sure to review the details provided on docs.microsoft.com at the following URL:
https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fenterprise%2Fcross-tenant-mailbox-migration&data=04%7C01%7CRoman.Powell%40microsoft.com%7C86bbb93851064c1976f508d8e7d6fd1e%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637514257853318974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HfpI4QdEqTg2fW4ovAcam2hjnnDBG6rs8U6IBfcBD9s%3D&reserved=0>

It is also recommended before running this script to review the script in a script editor or Notepad prior to running.

For general feedback and / or questions, please contact ***@***.******@***.***>.
This is not a support alias and should not be used if you are currently experiencing an issue and need immediate assistance.

Setting up key vault in the healthecind.onmicrosoft.com tenant

Name Account SubscriptionName Environment TenantId

________________________________

Azure subscription 1 (2be40411-f954-4... jeremy.cornwell@HealthECind.onm<mailto:jeremy.cornwell@HealthECind.onm>... Azure subscription 1 AzureCloud c7bc967c-4a9b-43ad-8def-afcc5a...
Exchange app given access to KeyVault healthecind-vault
Application healthecind_Friends_healthec_1462 created successfully in healthecind.onmicrosoft.com tenant with following permissions. MSGraph - User.Invite.All. Exchange - Mailbox
.Migration
Admin consent URI for healthecind.onmicrosoft.com tenant admin is -
redacted\SetupCrossTenantRelationshipForTargetTenant.ps1 : The term '=' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

  *   .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDoma ...

*           + CategoryInfo          : ObjectNotFound: (=:String) [SetupCrossTenan...argetTenant.ps1], CommandNotFoundException

*           + FullyQualifiedErrorId : CommandNotFoundException,SetupCrossTenantRelationshipForTargetTenant.ps1`

  *

-

**Comment by jcornwe** [comment]
Unfortunately, removing the quotes produces the same error.

**Comment by ropow** [comment]
Can you verify that you have the latest scripts from release? I just ran a target setup myself and did not hit this issue.

**Comment by jcornwe** [comment]
Having the updated code from yesterday resolved the issue.
