### ISSUE TITLE
Verifying OrganizationRelationship]..............[Failed]

### ISSUE THREAD

**Issue by jcornwe** [microsoft/cross-tenant#39]
I receive no errors on the two setup scripts and then when running the verification script for the target tenant the organization relationship is still reporting failed.

Is there a location to receive more assistance in troubleshooting? The output doesn't explain why.

**Comment by ropow** [comment]
Can you email ***@***.******@***.***> with the output of the verification script, and what parameters you are using running both the target and source setup.

Thanks,

Roman

From: jcornwe ***@***.***>
Sent: Thursday, March 18, 2021 9:29 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] Verifying OrganizationRelationship]..............[Failed] (#39)


I receive no errors on the two setup scripts and then when running the verification script for the target tenant the organization relationship is still reporting failed.

Is there a location to receive more assistance in troubleshooting? The output doesn't explain why.

-

**Comment by jcornwe** [comment]
The email address has been sanitized possibly? All I see is ****@*****

Thanks.

**Comment by ropow** [comment]
crosstenantmigrationpreview@service.microsoft.com is the support email address to send the information too.

**Comment by bateji** [comment]
Hello,
I believe I had a similar issue.
Ran the tenant scripts and after that I ran VerifySetup.ps1
This passed the AAD Application Verification but fails the Relationship verification.

When I ran the VerifySetup.ps1 on the Resource tenant instead, it passed. The article suggests it should be ran on the target tenant.
