### ISSUE TITLE
Line 256 - Prompt for Authentication results in reply URL mismatch

### ISSUE THREAD

**Issue by RT235** [microsoft/cross-tenant#57]
During the script process, the user copies the first URL and accepts the app permissions within the browser. Following this, pressing return in the PowerShell session prompts for authentication. Once authentication is given, the error is presented.

I have tried consenting to both URLs, tried authentication with/without MFA, authenticating with the source tenant admin as well. 

If I check the app that has been registered, before pressing return in PS, I can see that the redirect URL is office.com within Azure AD > App Registrations > Authentication > redirect (if that is of use).

Admin consent URI for xxxxx.onmicrosoft.com tenant admin is -
https://login.microsoftonline.com/xxxxx.onmicrosoft.com/adminconsent?client_id=5c53a70b-b548-45de-838c-64b5d7198301&redirect_uri=https://office.com
Admin consent URI for yyyyy.onmicrosoft.com tenant admin is -
https://login.microsoftonline.com/yyyyy..onmicrosoft.com/adminconsent?client_id=5c53a70b-b548-45de-838c-64b5d7198301&redirect_uri=https://office.com

Application details to be registered in organization relationship: ApplicationId: [ 5c53a70b-b548-45de-838c-64b5d7198301 ]. KeyVault secret Id: [ https://aaaaa.vault.azure.net:443/certificates/bbbbb/d861f72b6c30476c96201924ef584b72 ]. These values are available in variables $AppId and $CertificateId respectively
Please consent to the app for xxxxx.onmicrosoft.com before sending invitation to first.last@yyyyy.com:
![a](https://user-images.githubusercontent.com/84445335/118793982-0a72da80-b891-11eb-8de1-cd487f95338f.png)

**Comment by ropow** [comment]
Can you run the script using -UseAppAndCertGeneratedForSendingInvitation  and see if you do not receive the error.

Thanks,

Roman

**Comment by RT235** [comment]
> Can you run the script using -UseAppAndCertGeneratedForSendingInvitation and see if you do not receive the error.
> 
> Thanks,
> 
> Roman

Hi Roman, 

Thanks a lot for the suggestion, this resolved by issue.

**Comment by RT235** [comment]
Now resolved by adding the -UseAppAndCertGeneratedForSendingInvitation parameter.
