### ISSUE TITLE
Hardcored Contoso.onmicrosoft on line 801 Setupcrosstenantrelationshipfortargettenant.ps1

### ISSUE THREAD

**Issue by calvin2sr** [microsoft/cross-tenant#58]
I cannot execute with success the script setupcrosstenantrelationshipfortargettenant.ps1 because contoso.onmicrosoft.com is hardcoded in line 801.

Can you update and fix the script?

Thank you.

**Comment by Andy-0-Ryan** [comment]
Line 801 is in a section that is simply performing a check against your organization to confirm the Enable-OrganizationCustomization has been executed in the tenant. You can see from line 801 this is performing a -whatif only. The target DomainName does not matter. Line 672 is where the actual New-OrganizationRelationship is created as part of Run-ExchangeSetupForTargetTenant.
