### ISSUE TITLE
AADSTS50011 - failing on target consent prompt

### ISSUE THREAD

**Issue by kumar-debug** [microsoft/cross-tenant#59]
after running the script and getting the Admin consent URI .
I enter the URI link in the browser and grant the permission for the applications

and comes back to the powershell window and hit enter, i get new pop-up to sign-in and enters the target domains creds and gets the error message.

"AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'a0c73c16-a7e3-4564-9a95-2bdf47383716'. "

**Comment by ropow** [comment]
Please try running the script using the parameter -UseAppAndCertGeneratedForSendingInvitation

Thanks,

Roman
________________________________
From: kumar-debug ***@***.***>
Sent: Monday, May 31, 2021 4:01 PM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] AADSTS50011 - failing on target consent prompt (#59)


after running the script and getting the Admin consent URI .
I enter the URI link in the browser and grant the permission for the applications

and comes back to the powershell window and hit enter, i get new pop-up to sign-in and enters the target domains creds and gets the error message.

"AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'a0c73c16-a7e3-4564-9a95-2bdf47383716'. "

**Comment by kumar-debug** [comment]
thanks Roman, please could you share the line number ?

**Comment by ropow** [comment]
You wouldn't be adding this into the script, it would be one of the parameters you run the script with.

Ex..

SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain fabrikam.onmicrosoft.com -TargetTenantDomain contoso.onmicrosoft.com -ResourceTenantId <ContosoTenantId> -UseAppAndCertGeneratedForSendingInvitation


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by kumar-debug** [comment]
thanks a lot, it fixed it.
