### ISSUE TITLE
Problems running script - error on "Location" argument

### ISSUE THREAD

**Issue by davidlalim** [microsoft/cross-tenant#60]
Hi,

I´m running the script with following arguments:

.\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain xpto -ResourceTenantAdminEmail xpto -TargetTenantDomain xpto -ResourceTenantId xpto -SubscriptionId xpto -ResourceGroup "xpto" -KeyVaultName "xpto" -CertificateName "xpto" -CertificateSubject "CN=xpto" -AzureAppPermissions Exchange, MSGraph -UseAppAndCertGeneratedForSendingInvitation -KeyVaultAuditStorageAccountName "xpto" -KeyVaultAuditStorageResourceGroup "xpto"

The RG and KV is created without problems, but when goes to the next step gives me this error:

![image](https://user-images.githubusercontent.com/85165882/120310103-e9b57680-c2cd-11eb-938d-2a5efa2a6700.png)

Can anyone help me, please ?

BR
David Lalim

**Comment by ropow** [comment]
Good morning David,

You need to use the parameter -AzureResourceLocation when running the script, and supply the DisplayName of the location you wish to use.

Thanks,

Roman


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
From: davidlalim ***@***.***>
Sent: Tuesday, June 1, 2021 3:40 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] Problems running script - error on "Location" argument (#60)


Hi,

I´m running the script with following arguments:

.\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain xpto -ResourceTenantAdminEmail xpto -TargetTenantDomain xpto -ResourceTenantId xpto -SubscriptionId xpto -ResourceGroup "xpto" -KeyVaultName "xpto" -CertificateName "xpto" -CertificateSubject "CN=xpto" -AzureAppPermissions Exchange, MSGraph -UseAppAndCertGeneratedForSendingInvitation -KeyVaultAuditStorageAccountName "xpto" -KeyVaultAuditStorageResourceGroup "xpto"

The RG and KV is created without problems, but when goes to the next step gives me this error:

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F85165882%2F120310103-e9b57680-c2cd-11eb-938d-2a5efa2a6700.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7C3aa570d6fc2a4e28e08e08d924e9ab56%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637581408290817142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CNi30%2BIdt5PlGIZoZH3C%2FljN%2BPusYVkPpcR2i0dhTL4%3D&reserved=0>

Can anyone help me, please ?

BR
David Lalim

**Comment by davidlalim** [comment]
Hi Roman,

Thanks for your quickly reply.

The issue that i reported is already solved, I saw that there was another closed case with the same problem.

Now I have another issue on the migration step when we run the PS Script Verifysetup.ps1:

***@***.***D7579E.D8EA9320]

Can you please help me ? I’m running on the Source Tenant.

Tks
BR
David Lalim
[ki]<http://www.knowledgeinside.pt/niodo>
Tel.: +351 210 174 216
Tlm.: +351 938 034 913
Polo Tecnológico de Lisboa
Rua António Champalimaud, Edificio 3 Sala 218
1600-514 Lisboa
[facebook]<https://www.facebook.com/knowledgeinside> [linkedin] <https://www.linkedin.com/company/2608410/admin/>  [youtube] <https://www.youtube.com/channel/UCMp0SySc2MHxvXyOoXDhRKA>

**Comment by Raton-Laveur** [comment]
> The issue that i reported is already solved, I saw that there was another closed case with the same problem.
Please specify the issue number. I am having the same problem but you're not providing enough info for others to solve it.

**Comment by davidlalim** [comment]
Hi Raton,

Below, the closed case with the same problem:

https://github.com/microsoft/cross-tenant/issues/54
David Lalim
[ki]<http://www.knowledgeinside.pt/niodo>
Tel.: +351 210 174 216
Tlm.: +351 938 034 913
Polo Tecnológico de Lisboa
Rua António Champalimaud, Edificio 3 Sala 218
1600-514 Lisboa
[facebook]<https://www.facebook.com/knowledgeinside> [linkedin] <https://www.linkedin.com/company/2608410/admin/>  [youtube] <https://www.youtube.com/channel/UCMp0SySc2MHxvXyOoXDhRKA>

**Comment by ropow** [comment]
David,

Can you please sent email to crosstenantmigrationpreview@service.microsoft.com with the parameters used when running the verify script and the output you received.

Thanks,

Roman

**Comment by eddyz1122** [comment]
Hi There,

I had the same problem. I was able to overcome it by including the below.

`-KeyVaultAuditStorageAccountLocation "UK South"`

Hope this helps,

Ed
