### ISSUE TITLE
getting error while running PowerShell after Keyvault generation - WARNING: System.ArgumentException: Argument passed in is not serializable.

### ISSUE THREAD

**Issue by k4kunal354** [microsoft/cross-tenant#61]
Hi Team,

i am getting an error after Script creates the unique Keyvault in Azure. saying WARNING: System.ArgumentException: Argument passed in is not serializable. 
![Error Screenshot](https://user-images.githubusercontent.com/85727919/121641997-884f8d80-caad-11eb-93f7-ae60165ebb70.JPG)

**Comment by ropow** [comment]
Be sure you are passing -AzureResourceLocation, and if you are using Storage Auditing, also pass -KeyVaultAuditStorageAccountLocation

Thanks,

Roman

From: k4kunal354 ***@***.***>
Sent: Thursday, June 10, 2021 11:38 PM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] getting error while running PowerShell after Keyvault generation - WARNING: System.ArgumentException: Argument passed in is not serializable. (#61)


Hi Team,

i am getting an error after Script creates the unique Keyvault in Azure. saying WARNING: System.ArgumentException: Argument passed in is not serializable.
[Error Screenshot]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F85727919%2F121641997-884f8d80-caad-11eb-93f7-ae60165ebb70.JPG&data=04%7C01%7CRoman.Powell%40microsoft.com%7Cdb332dabd5c54bd9e6b008d92ca36ec2%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637589902733128964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=G63d5ErUdJxA%2FrPxDz344h148xKQCxrXWTMg%2BGezK%2BU%3D&reserved=0>

-
