### ISSUE TITLE
AADSTS50011 

### ISSUE THREAD

**Issue by nmixeri3** [microsoft/cross-tenant#62]
Getting this error after copy and pasting the URLs.
![image](https://user-images.githubusercontent.com/86121212/122593977-07a00c80-d02c-11eb-879d-f82ce9cda755.png)

I tried adding UseAppAndCertGeneratedForSendingInvitation but this results in -
![image](https://user-images.githubusercontent.com/86121212/122594388-8eed8000-d02c-11eb-9ae0-46fa0d89e128.png)

Any thoughts?

**Comment by ropow** [comment]
Good morning. Can you please use InPrivate/Incognito when pasting the URL's.

Thanks,

Roman

From: nmixeri3 ***@***.***>
Sent: Friday, June 18, 2021 9:59 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] AADSTS50011 (#62)


Getting this error after copy and pasting the URLs.
[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F86121212%2F122593977-07a00c80-d02c-11eb-879d-f82ce9cda755.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7Caaa14b2c6bc44593de3308d9327a6a9b%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637596323635133427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=n7RJTpg2%2BLcC84Y2j3b1gcD9tD%2F%2FeCdqpz%2B%2F%2FOjlkKU%3D&reserved=0>

I tried adding UseAppAndCertGeneratedForSendingInvitation but this results in -
[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F86121212%2F122594388-8eed8000-d02c-11eb-9ae0-46fa0d89e128.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7Caaa14b2c6bc44593de3308d9327a6a9b%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637596323635133427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LvQboXK8w2549ySyabiPDY6kApCPoZp%2Bz9n2wxl9jNI%3D&reserved=0>

Any thoughts?

-

**Comment by nmixeri3** [comment]
I have done so with the same error.

**Comment by ropow** [comment]
Can you please send email to ***@***.******@***.***> with the parameters you are using to run setup without redaction on anything.

Thanks,

Roman

**Comment by nmixeri3** [comment]
Hmm Im not seeing the email you're posting on here

**Comment by ropow** [comment]
Well that's annoying!

crosstenantmigrationpreview@service.microsoft.com is the email address

**Comment by nmixeri3** [comment]
Looks like I had the source and target tenant backwards. Thank you.
