### ISSUE TITLE
Cannot validate argument on parameter 'SkuName'

### ISSUE THREAD

**Issue by arennvick** [microsoft/cross-tenant#64]
D:\new\SetupCrossTenantRelationshipForTargetTenant.ps1 : Cannot validate argument on parameter 'SkuName'. The argument "" does not belong to the set
"Standard_LRS,Standard_ZRS,Standard_GRS,Standard_RAGRS,Premium_LRS,Premium_ZRS,Standard_GZRS,Standard_RAGZRS" specified by the ValidateSet attribute. Supply an argument that is in the set
and then try the command again.
At line:1 char:1
+ .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDoma ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [SetupCrossTenan...argetTenant.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,SetupCrossTenantRelationshipForTargetTenant.ps1

**Comment by ropow** [comment]
Good morning. When using StorageAudit you also need to supply the parameter KeyVaultAuditStorageAccountLocation, generally just using Standard_GRS based on most subscriptions.

Thanks,

Roman

From: arennvick ***@***.***>
Sent: Sunday, June 20, 2021 6:21 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] Cannot validate argument on parameter 'SkuName' (#64)


D:\new\SetupCrossTenantRelationshipForTargetTenant.ps1 : Cannot validate argument on parameter 'SkuName'. The argument "" does not belong to the set
"Standard_LRS,Standard_ZRS,Standard_GRS,Standard_RAGRS,Premium_LRS,Premium_ZRS,Standard_GZRS,Standard_RAGZRS" specified by the ValidateSet attribute. Supply an argument that is in the set
and then try the command again.
At line:1 char:1

  *   .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDoma ...

*           + CategoryInfo          : InvalidData: (:) [SetupCrossTenan...argetTenant.ps1], ParameterBindingValidationException

*           + FullyQualifiedErrorId : ParameterArgumentValidationError,SetupCrossTenantRelationshipForTargetTenant.ps1

  *

-

**Comment by arennvick** [comment]
Hi Roman,

Thank you for the response.

So should it be something like,

-KeyVaultAuditStorageAccountLocation Standard_GRS

Thank you
Antonio Rennvick
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ropow** [comment]
That is correct.

**Comment by arennvick** [comment]
im getting the below error.

[cid:b9066a80-2d17-4d31-bb47-96ce10d04366]

Thank You
Antonio Rennvick Annoson


________________________________

**Comment by arennvick** [comment]
Antonio,

Can you use the parameter -UseAppAndCertGeneratedForSendingInvitation and try again.

Thanks,

Roman

From: Antonio Rennvick ***@***.***>
Sent: Saturday, June 26, 2021 10:12 PM
To: microsoft/cross-tenant ***@***.***>; microsoft/cross-tenant ***@***.***>; Cross-Tenant Mailbox Migration Preview ***@***.***>
Cc: Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/cross-tenant] Cannot validate argument on parameter 'SkuName' (#64)

im getting the below error.

***@***.***D76C04.5D58AB00]

Thank You
Antonio Rennvick Annoson


________________________________

**Comment by arennvick** [comment]
Hi Roman,

Thank you so much for the support. all worked well.

Thank You
Antonio Rennvick Annoson


________________________________
From: Roman Powell ***@***.***>
Sent: Monday, June 28, 2021 10:30 PM
To: ***@***.*** ***@***.***>; ***@***.*** ***@***.***>; ***@***.*** ***@***.***>; Cross-Tenant Mailbox Migration Preview ***@***.***>
Cc: ***@***.*** ***@***.***>
Subject: RE: [microsoft/cross-tenant] Cannot validate argument on parameter 'SkuName' (#64)


Antonio,



Can you use the parameter -UseAppAndCertGeneratedForSendingInvitation and try again.



Thanks,



Roman



From: Antonio Rennvick ***@***.***>
Sent: Saturday, June 26, 2021 10:12 PM
To: microsoft/cross-tenant ***@***.***>; microsoft/cross-tenant ***@***.***>; Cross-Tenant Mailbox Migration Preview ***@***.***>
Cc: Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/cross-tenant] Cannot validate argument on parameter 'SkuName' (#64)



im getting the below error.



***@***.***D76C04.5D58AB00]



Thank You

Antonio Rennvick Annoson





________________________________
