### ISSUE TITLE
Get-OrganizationRelationship results in error after running both scripts

### ISSUE THREAD

**Issue by nmixeri3** [microsoft/cross-tenant#65]
Does anyone know what I can do to see where the org relationship is incorrect?

![image](https://user-images.githubusercontent.com/86121212/122782394-4e814280-d276-11eb-8581-b7c560a86e48.png)

**Comment by ropow** [comment]
Good morning,

Can you please send mail to crosstenantmigrationpreview@service.microsoft.com with your source and target domains. Also, did running the setup script state the OrgRelationship was created successfully?

Thanks,

Roman

**Comment by nmixeri3** [comment]
Started working out of no where.
