### ISSUE TITLE
You cannot call a method on a null-valued expression. At line:1 char:1

### ISSUE THREAD

**Issue by Arne-RFA** [microsoft/cross-tenant#66]
PowerShell version (on W10)
```
PS C:\Temp\cross-tenant-main> $PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1023
```

Before running script (from the main branch)

```
Connect-ExchangeOnline -UserPrincipalName global-admin@targetpublicdomain
```

Script invoked with 
```
.\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain <source>.onmicrosoft.com -TargetTenantDomain <target>.onmicrosoft.com -ResourceTenantAdminEmail Admin@<sourcepublicdomain> -ResourceTenantId <redacted> -SubscriptionId <redacted> -ResourceGroup "<redacted>" -KeyVaultName "JC-G-Migration-Vault" -AzureResourceLocation "West US" -CertificateName "JC-G-Migration-Cert" -CertificateSubject "<redacted>" -AzureAppPermissions Exchange, MSGraph -MigrationEndpointMaxConcurrentMigrations 20 -UseAppAndCertGeneratedForSendingInvitation
```

After invoking script, there was a single modern auth prompt, which from the page https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide I presumed was for the target

Script errors with 

```
Verifying that your script is up to date with the latest changes.

Beginning download of SetupCrossTenantRelationshipForTargetTenant.ps1 and creation of temporary files.

Verifying that a valid location was specified for Azure


You are using the latest version of the script. Removing temporary files and proceeding with setup.
WARNING: TenantId '<redacted>' contains more than one active subscription. First one will be
selected for further use. To select another subscription, use Set-AzContext.
Setting up key vault in the <redacted>.onmicrosoft.com tenant

Name                                     Account             SubscriptionName    Environment         TenantId
----                                     -------             ----------------    -----------         --------
<redacted> (<redacted> <redacted>. <redacted>. AzureCloud          <redacted>
Resource Group <redacted> successfully created
KeyVault JC-G-Migration-Vault successfully created
Exchange app given access to KeyVault JC-G-Migration-Vault
Self signed certificate requested in key vault - JC-G-Migration-Vault. Certificate name - JC-G-Migration-Cert
Certificate JC-G-Migration-Cert successfully created
C:\Temp\cross-tenant-main\SetupCrossTenantRelationshipForTargetTenant.ps1 : You cannot call a method on a null-valued
expression.
At line:1 char:1
+ .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDoma ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [SetupCrossTenan...argetTenant.ps1], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,SetupCrossTenantRelationshipForTargetTenant.ps1
```

**Comment by ropow** [comment]
Arne,

Can you run the script a second time with -Verbose

Thanks,

Roman

From: Arne-RFA ***@***.***>
Sent: Monday, June 28, 2021 1:41 PM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] You cannot call a method on a null-valued expression. At line:1 char:1 (#66)


PowerShell version (on W10)

PS C:\Temp\cross-tenant-main> $PSVersionTable.PSVersion

Major  Minor  Build  Revision

-----  -----  -----  --------

5      1      19041  1023

Before running script

Connect-ExchangeOnline -UserPrincipalName ***@***.***

Script invoked with

.\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain <source>.onmicrosoft.com -TargetTenantDomain <target>.onmicrosoft.com -ResourceTenantAdminEmail Admin@<sourcepublicdomain> -ResourceTenantId <redacted> -SubscriptionId <redacted> -ResourceGroup "<redacted>" -KeyVaultName "JC-G-Migration-Vault" -AzureResourceLocation "West US" -CertificateName "JC-G-Migration-Cert" -CertificateSubject "<redacted>" -AzureAppPermissions Exchange, MSGraph -MigrationEndpointMaxConcurrentMigrations 20 -UseAppAndCertGeneratedForSendingInvitation

After invoking script, there was a single modern auth prompt, which from the page https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fenterprise%2Fcross-tenant-mailbox-migration%3Fview%3Do365-worldwide&data=04%7C01%7CRoman.Powell%40microsoft.com%7C5881b08f15874905445508d93a75166a%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637605096846253447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Vx4IkaO2YTRjw3xWxDzw1FzmfGfTQtCzGjYI1nV1LVY%3D&reserved=0> I presumed was for the target

Script errors with

Verifying that your script is up to date with the latest changes.



Beginning download of SetupCrossTenantRelationshipForTargetTenant.ps1 and creation of temporary files.



Verifying that a valid location was specified for Azure





You are using the latest version of the script. Removing temporary files and proceeding with setup.

WARNING: TenantId '<redacted>' contains more than one active subscription. First one will be

selected for further use. To select another subscription, use Set-AzContext.

Setting up key vault in the <redacted>.onmicrosoft.com tenant



Name                                     Account             SubscriptionName    Environment         TenantId

----                                     -------             ----------------    -----------         --------

<redacted> (<redacted> <redacted>. <redacted>. AzureCloud          <redacted>

Resource Group <redacted> successfully created

KeyVault JC-G-Migration-Vault successfully created

Exchange app given access to KeyVault JC-G-Migration-Vault

Self signed certificate requested in key vault - JC-G-Migration-Vault. Certificate name - JC-G-Migration-Cert

Certificate JC-G-Migration-Cert successfully created

C:\Temp\cross-tenant-main\SetupCrossTenantRelationshipForTargetTenant.ps1 : You cannot call a method on a null-valued

expression.

At line:1 char:1

+ .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDoma ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidOperation: (:) [SetupCrossTenan...argetTenant.ps1], RuntimeException

    + FullyQualifiedErrorId : InvokeMethodOnNull,SetupCrossTenantRelationshipForTargetTenant.ps1

-

**Comment by Arne-RFA** [comment]
ran same command as before with -Verbose

No errors until 

```
Certificate JC-G-Migration-Cert successfully created
VERBOSE: Creating an application in <target>.onmicrosoft.com
C:\Temp\cross-tenant-main\SetupCrossTenantRelationshipForTargetTenant.ps1 : You cannot call a method on a null-valued
expression.
At line:1 char:1
+ .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDoma ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [SetupCrossTenan...argetTenant.ps1], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,SetupCrossTenantRelationshipForTargetTenant.ps1
```

**Comment by marcelbechtle** [comment]
I had the same problem: I was able to solve it by changing the value of the parameter "-TargetTenantDomain" from "companyname.onmicrosoft.com" to my primary domain (customdomain.com).

**Comment by SteveS-ooaj** [comment]
I'm receiving the same issue. Changed it from domain.onmicrosoft.com to domain.onmicrosoft.com with same results.

Self signed certificate requested in key vault - aaojmigkvv. Certificate name - 3928TenantFriendingAppSecret
VERBOSE: Looking for certificate 3928TenantFriendingAppSecret. Attempt - 1
VERBOSE: Certificate not found, waiting 5 secs and looking again.
VERBOSE: Looking for certificate 3928TenantFriendingAppSecret. Attempt - 2
VERBOSE: Certificate not found, waiting 5 secs and looking again.
VERBOSE: Looking for certificate 3928TenantFriendingAppSecret. Attempt - 3
VERBOSE: Certificate not found, waiting 5 secs and looking again.
VERBOSE: Looking for certificate 3928TenantFriendingAppSecret. Attempt - 4
VERBOSE: Certificate not found, waiting 5 secs and looking again.
VERBOSE: Looking for certificate 3928TenantFriendingAppSecret. Attempt - 5
VERBOSE: Certificate not found, waiting 5 secs and looking again.
VERBOSE: Returning cert -
Certificate 3928TenantFriendingAppSecret successfully created
VERBOSE: Creating an application in caaak.com
C:\scripts\SetupCrossTenantRelationshipForTargetTenant.ps1 : You cannot call a method on a null-valued expression.
At line:1 char:1
+ .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantAdmi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [SetupCrossTenan...argetTenant.ps1], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,SetupCrossTenantRelationshipForTargetTenant.ps1

**Comment by ropow** [comment]
Steve,

Generally this is a generic timeout error. As long as you have not deleted the created ResourceGroup,KeyVault, etc.. just rerunning the script with the same parameters should get past this error.

Roman

**Comment by SteveS-ooaj** [comment]
It seems to locate the certificate though. It fails on app creation. 

Certificate 3928TenantFriendingAppSecret successfully created
VERBOSE: Creating an application in caaak.com <http://caaak.com/>
C:\scripts\SetupCrossTenantRelationshipForTargetTenant.ps1 : You cannot call a method on a null-valued expression.

**Comment by Arne-RFA** [comment]
Apologies for not updating.

After communicating with @ropow ( a week ago) it just started working for me. I had initially been deleing the Key Store and the Resource group, and one time I did not, and then second time I ran (without deleting the Key Store and Resource Group) and it worked. I would agree that it appears to be a timeout somewhere.
