### ISSUE TITLE
Login error after AzureAD App creation.

### ISSUE THREAD

**Issue by JermCool** [microsoft/cross-tenant#67]
Just after the script creates the AAD enterprise application "targetDomain_Friends_sourceDomain_####" and I approve the app for the organization (both following the link and through the Azure portal), I'm getting prompted with another login window.  I re-enter my Global Admin credentials for the target domain, but get the error "AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'a0c73c16-a7e3-4564-9a95-2bdf47383716'. "  This application ID is the same every time I encounter the error, even though the new enterprise application ID has a different number.  There's no way to go back to re-enter credentials and the script bombs out with a "User canceled authentication" message.

I've looked through all the enterprise applications in the target domain and for the life of me I cannot find the application ID referenced in the error message.
![login_window](https://user-images.githubusercontent.com/86855249/124328938-6478e800-db3f-11eb-94f1-6f2d1258998b.png)
![error_msg](https://user-images.githubusercontent.com/86855249/124328953-6cd12300-db3f-11eb-8e63-fe7e5eb97284.PNG)
![AppMissing](https://user-images.githubusercontent.com/86855249/124329219-f41e9680-db3f-11eb-9ed1-551269d82b50.PNG)

**Comment by kumar-debug** [comment]
from the contributor 
"
Please try running the script using the parameter -UseAppAndCertGeneratedForSendingInvitation "

**Comment by JermCool** [comment]
Thank you Kumar!!!  It finally completed successfully!
![itworks](https://user-images.githubusercontent.com/86855249/124332910-91c99400-db47-11eb-9a0f-fa4152faff58.PNG)
