### ISSUE TITLE
the parent object could not be found

### ISSUE THREAD

**Issue by kumar-debug** [microsoft/cross-tenant#68]
this is on the source side, when running with all the parameters.

Getting this error.

VERBOSE : Creating Organization Relationship: Domain_Sync_9193 in domain.onmicrosoft.com
The parent object for Domain_Sync_9193 could not be found. Please check that domain.onmicrosoft.com \federation exists.

**Comment by ropow** [comment]
Kumar,

What did you specify in the parameters?

Thanks,

Roman

From: kumar-debug ***@***.***>
Sent: Friday, July 2, 2021 2:53 PM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] the parent object could not be found (#68)


this is on the source side, when running with all the parameters.

Getting this error.

VERBOSE : Creating Organization Relationship: Domain_Sync_9193 in domain.onmicrosoft.com
The parent object for Domain_Sync_9193 could not be found. Please check that domain.onmicrosoft.com \federation exists.

-

**Comment by kumar-debug** [comment]
The parameters are 

-ResourceTenantDomain  -targetTenantDomain -TargetTenantID -sourceMailboxmovepublishedScopes -applicationID

**Comment by ropow** [comment]
Please include the values you used. If you do not want them on GitHub please send a separate email to crosstenantmigrationpreview@microsoft.com.

Thanks,

Roman

**Comment by kumar-debug** [comment]
it was a tenant issue, its resolved now.
