### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by a200411044** [microsoft/cross-tenant#69]
I have already set up both the Source or Target Tenant but stuck on the next step

1. Can show me an example of "users.csv" which will used in the Create Migration batches step?
![image](https://user-images.githubusercontent.com/38806611/125885994-d81a60ee-b80e-4cad-8aac-2e9bcf06c47e.png)

2. How to set objects and attributes in the target organization that will match with the sources tenant?  
![image](https://user-images.githubusercontent.com/38806611/125886025-ef2b6fdf-1d2d-4c51-a72d-e0acf973c539.png)

Hope can make a easier version for (https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)

**Comment by ropow** [comment]
Good morning.

There is a planned update to the documentation to include a sample CSV file. At the moment though this is what it should look like:

***@***.***D77A26.A7CE2590]

As far as how to set objects and attributes on the target, if you go to the documentation > Frequently Asked Questions the first item is a sample script for copying the attributes from the source and importing them to the target.

Thanks,

Roman

From: a200411044 ***@***.***>
Sent: Thursday, July 15, 2021 8:14 PM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] Help (#69)


I have already set up both the Source or Target Tenant but stuck on the next step

  1.  Can show me an example of "users.csv" which will used in the Create Migration batches step?
[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F38806611%2F125885994-d81a60ee-b80e-4cad-8aac-2e9bcf06c47e.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7C07dbcc40d98e4208117408d94807b8b6%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637620020339279178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R%2F6p0qYjMGwb8qUUr7CGSD29YY4U92cTQcSk%2FVMyQ8I%3D&reserved=0>
  2.  How to set objects and attributes in the target organization that will match with the sources tenant?
[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F38806611%2F125886025-ef2b6fdf-1d2d-4c51-a72d-e0acf973c539.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7C07dbcc40d98e4208117408d94807b8b6%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637620020339289135%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=h1ZjrvrgS5e%2BDSv7nPvSh15bwEBBHwFBZWE2iNdWATo%3D&reserved=0>

Hope can make a easier version for (https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fenterprise%2Fcross-tenant-mailbox-migration%3Fview%3Do365-worldwide&data=04%7C01%7CRoman.Powell%40microsoft.com%7C07dbcc40d98e4208117408d94807b8b6%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637620020339289135%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EyoMSZ%2F812VyHHf5cx8twrY9yEekEwRGeJksRCudL6g%3D&reserved=0>)

-

**Comment by ropow** [comment]
Sorry, the sample script moved down, but it is at the top of the FAQ.

Roman

From: Roman Powell
Sent: Friday, July 16, 2021 9:41 AM
To: 'microsoft/cross-tenant' ***@***.***>; microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: RE: [microsoft/cross-tenant] Help (#69)

Good morning.

There is a planned update to the documentation to include a sample CSV file. At the moment though this is what it should look like:

***@***.***D77A28.1C14E190]

As far as how to set objects and attributes on the target, if you go to the documentation > Frequently Asked Questions the first item is a sample script for copying the attributes from the source and importing them to the target.

Thanks,

Roman

From: a200411044 ***@***.******@***.***>>
Sent: Thursday, July 15, 2021 8:14 PM
To: microsoft/cross-tenant ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [microsoft/cross-tenant] Help (#69)


I have already set up both the Source or Target Tenant but stuck on the next step

  1.  Can show me an example of "users.csv" which will used in the Create Migration batches step?
[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F38806611%2F125885994-d81a60ee-b80e-4cad-8aac-2e9bcf06c47e.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7C07dbcc40d98e4208117408d94807b8b6%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637620020339279178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R%2F6p0qYjMGwb8qUUr7CGSD29YY4U92cTQcSk%2FVMyQ8I%3D&reserved=0>
  2.  How to set objects and attributes in the target organization that will match with the sources tenant?
[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F38806611%2F125886025-ef2b6fdf-1d2d-4c51-a72d-e0acf973c539.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7C07dbcc40d98e4208117408d94807b8b6%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637620020339289135%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=h1ZjrvrgS5e%2BDSv7nPvSh15bwEBBHwFBZWE2iNdWATo%3D&reserved=0>

Hope can make a easier version for (https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fenterprise%2Fcross-tenant-mailbox-migration%3Fview%3Do365-worldwide&data=04%7C01%7CRoman.Powell%40microsoft.com%7C07dbcc40d98e4208117408d94807b8b6%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637620020339289135%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EyoMSZ%2F812VyHHf5cx8twrY9yEekEwRGeJksRCudL6g%3D&reserved=0>)

-

**Comment by a200411044** [comment]
i follow the sample script and i got this error, please help.

The CSV file contains one or more unrecognizable columns. Please remove these columns and re-submit the file. Unknown
columns: "admin"
    + CategoryInfo          : NotSpecified: (:) [], CsvUnknownColumnsException
    + FullyQualifiedErrorId : [Server=PSAPR01MB3895,RequestId=37aa0213-7709-462c-9496-7e6f618a2771,TimeStamp=7/19/2021
    9:34:16 AM] [FailureCategory=Cmdlet-CsvUnknownColumnsException] 83A134D1
    + PSComputerName        : outlook.office365.com

**Comment by a200411044** [comment]
Thanks, finally kicked off the migration batch, hoping everything goes well.
![image](https://user-images.githubusercontent.com/38806611/126142079-17a42f7c-95dc-4b47-88bf-14f0af31e675.png)

**Comment by a200411044** [comment]
![image](https://user-images.githubusercontent.com/38806611/126147596-b5ba9517-f215-4627-99d7-7edb4b5e5ec3.png)
New problem comes...

**Comment by ropow** [comment]
Good morning,

This is due to licensing the mail user object before it had an ExchangeGuid assigned, or creating a mailbox instead of mail user. It is suggested that you do not license users until after all values have been applied from the source, or after migration.

Thanks,

Roman

**Comment by a200411044** [comment]
> Good morning, This is due to licensing the mail user object before it had an ExchangeGuid assigned, or creating a mailbox instead of mail user. It is suggested that you do not license users until after all values have been applied from the source, or after migration. Thanks, Roman From: a200411044 ***@***.***> Sent: Monday, July 19, 2021 3:38 AM To: microsoft/cross-tenant ***@***.***> Cc: Roman Powell ***@***.***>; Comment ***@***.***> Subject: Re: [microsoft/cross-tenant] Help (#69) [image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F38806611%2F126147596-b5ba9517-f215-4627-99d7-7edb4b5e5ec3.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7C40dadde85ad140ef8b4308d94aa13c5b%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637622878639749609%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GvWKUQR%2FoqBSVm1gaHpxxXGLp0kkwWuj8I6H5UbzMMM%3D&reserved=0> New problem comes... - You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcross-tenant%2Fissues%2F69%23issuecomment-882440960&data=04%7C01%7CRoman.Powell%40microsoft.com%7C40dadde85ad140ef8b4308d94aa13c5b%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637622878639759566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pNBtN4CGpejB5jYCxzcpa7cNKhPekjMHAWB6oQZJKv0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPUHY6HRCCFPGQXYNJNZKB3TYP57JANCNFSM5AOXQMLQ&data=04%7C01%7CRoman.Powell%40microsoft.com%7C40dadde85ad140ef8b4308d94aa13c5b%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637622878639759566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UaTpJ0YFded%2Bt2Bm7lv3z%2BUX7AptzovTb9fiaQYC%2Fog%3D&reserved=0>.

Thanks for the reply, but how to create MailUser correctly? I've tried creating in powershell by using New-Mailuser or creating in contacts under EAC either it was successful. Could you please guide me? Thank you.

**Comment by a200411044** [comment]
![image](https://user-images.githubusercontent.com/38806611/126259297-ec83351d-7a18-4971-ab4f-76673564d824.png)
One problem sloved, another problem comes, please advise me if i have missed something.

**Comment by a200411044** [comment]
![image](https://user-images.githubusercontent.com/38806611/126262696-b46ba867-868c-41f7-b228-a82aa50559d4.png)
Please check my setting, much thanks

**Comment by ropow** [comment]
Good morning,

You need to add not only the LegacyExchangeDn as an X500 address, but all existing X500 addresses on the source mailbox, to the target user.

In the documentation, under Frequently Asked Questions, there is a sample script for copying all needed properties from the source object, and then creating the target objects with the needed values.

Thanks,

Roman

**Comment by a200411044** [comment]
> Good morning, You need to add not only the LegacyExchangeDn as an X500 address, but all existing X500 addresses on the source mailbox, to the target user. In the documentation, under Frequently Asked Questions, there is a sample script for copying all needed properties from the source object, and then creating the target objects with the needed values. Thanks, Roman From: a200411044 ***@***.***> Sent: Monday, July 19, 2021 9:37 PM To: microsoft/cross-tenant ***@***.***> Cc: Roman Powell ***@***.***>; Comment ***@***.***> Subject: Re: [microsoft/cross-tenant] Help (#69) [image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F38806611%2F126262696-b46ba867-868c-41f7-b228-a82aa50559d4.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7C3f20f1f2dbd74ad27f5f08d94b380a81%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637623526440736300%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nExxNmNT1%2FiduAzlXE%2F69aUQh0CeM4TC118J9KJKv58%3D&reserved=0> Please check my setting, much thanks - You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcross-tenant%2Fissues%2F69%23issuecomment-883045912&data=04%7C01%7CRoman.Powell%40microsoft.com%7C3f20f1f2dbd74ad27f5f08d94b380a81%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637623526440746296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=c%2FKLuoRCTd5kaFgSz8R%2Fe4z2ycK7URtyAdSLQ562sqs%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPUHY6D26QHMDORS4QF4I7DTYT4PPANCNFSM5AOXQMLQ&data=04%7C01%7CRoman.Powell%40microsoft.com%7C3f20f1f2dbd74ad27f5f08d94b380a81%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637623526440746296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ojUI3MxOxQCa3MfkBj4BAydbNvpi9eytV2hwhFDjNvw%3D&reserved=0>.

Hi 
First of all, thanks for your help I have successfully migrated to the new tenant, however when i tried to set up the account on the outlook, it shows "Something went wrong"  but the webmail(which is the web app on office.com) works totally fine. Do you have any ideas on this case? Please advise.

Much Thanks

**Comment by a200411044** [comment]
Attachment revised 

![image](https://user-images.githubusercontent.com/38806611/126742145-569c6881-4bb3-4ba1-a6f6-ea6f713ce4fe.png)

**Comment by ropow** [comment]
Please open a service request for this issue. Issues with setting up the Outlook profile is outside of the scope of this support channel.

Thanks,

Roman

**Comment by andytuke-jisc** [comment]
I had a load of issues with the example script to recreate the users objects with the relevant attributes copied. The Get-Mailbox cmdlet to extract the user attributes didn't seem to output the properties Firstame and LastName, and then in the New-MailUser step, running it on a on-premise Exchange complained about using -MicrosoftOnlineServicesID $mosi 
I ended up writing my own scripts and passed in a UPN instead.  Is the supplied script aimed at none hybrid Exchange?

**Comment by ropow** [comment]
Andy,

Thanks for the comments on this, we probably need to have samples separate for Hybrid & Cloud. I wrote this specifically for cloud based but the document was updated with some stuff regarding On Premises.

Thanks,

Roman
