### ISSUE TITLE
A valid Azure location was not specified,

### ISSUE THREAD

**Issue by andyonline2k21** [microsoft/cross-tenant#71]
Trying to run this script, it doesn't accept any locations I've tried.
any advice?

.\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain source.onmicrosoft.com -TargetTenantDomain destination.onmicrosoft.com -ResourceTenantId 1231413f09 -SubscriptionId 114151515 -resourcetenantadminemail admin@onmicrosoft.com -ResourceGroup "Cross-TenantMoves" -KeyVaultName "Cross-TenantMovesVault" -KeyVaultAuditStorageAccountLocation "UK South" -azureresourcelocation "UK South"

All i get is: **A valid Azure location was not specified**

**Comment by ropow** [comment]
Hello Andy,

Have you tried without -KeyVaultAuditStorageAccountLocation? This is only needed if you're using the other storage parameters.

Also, can you provide a verbose output when running the script?

Thanks,

Roman

From: andyonline2k21 ***@***.***>
Sent: Monday, July 26, 2021 8:50 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] A valid Azure location was not specified, (#71)


Trying to run this script, it doesn't accept any locations I've tried.
any advice?

.\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain source.onmicrosoft.com -TargetTenantDomain destination.onmicrosoft.com -ResourceTenantId 1231413f09 -SubscriptionId 114151515 -resourcetenantadminemail ***@***.******@***.***> -ResourceGroup "Cross-TenantMoves" -KeyVaultName "Cross-TenantMovesVault" -KeyVaultAuditStorageAccountLocation "UK South" -azureresourcelocation "UK South"

All i get is: A valid Azure location was not specified

-

**Comment by andyonline2k21** [comment]
i did yes, thanks for the reply.
The result is the same.
I tried adding -verbose and no difference to error message.

**Comment by ropow** [comment]
Can you include the output with verbose.

Thanks,

Roman

**Comment by andyonline2k21** [comment]
PS C:\Users\andy-admin> .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain source.onmicrosoft.com -TargetTenantDomain destination.onmicrosoft.com -ResourceTenantId 777cd8e1-d098-4127-9de5-7840f3443f09 -SubscriptionId 645473a2-62c5-4bab-8a6d-837c0d96587c -resourcetenantadminemail Andy-admin@source.onmicrosoft.com -ResourceGroup "Cross-TenantMoves" -KeyVaultName "Cross-TenantMovesVault" -azureresourcelocation "UK South" -verbose


Welcome to the Cross-tenant mailbox migration preview! Before running this script, please be sure to review the details provided on docs.microsoft.com at the following URL:
https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration

It is also recommended before running this script to review the script in a script editor or Notepad prior to running.

For general feedback and / or questions, please contact crosstenantmigrationpreview@service.microsoft.com.
This is not a support alias and should not be used if you are currently experiencing an issue and need immediate assistance.


Confirm: Configure Cross-Tenant mailbox migration preview.

If you are ready to begin configuring your tenants, select 'Y'.
If you need to review any additional details and proceed at a later time, select 'N'.

Do you wish to proceed?
[Y] Yes  [N] No  [?] Help (default is "N"): y

We are verifying that you are using the latest version of the script.

This requires that we download the latest version of the script from GitHub to compare with your local copy.
This file will be stored on your local computer temporarily, as well as overwrite your existing script file if it is out of date.

Confirm: Allow for download from GitHub.

If you are ready to begin this step, select 'Y'.
If you would prefer to manually download the scripts to make sure you have the latest version, select 'N'
[Y] Yes  [N] No  [?] Help (default is "N"): y

Beginning verification steps.

Verifying ability to create a new organization relationship in the tenant.
Creating a new Remote PowerShell session using Modern Authentication for implicit remoting of "New-OrganizationRelationship" command ...
What if: Creating organization relationship "Contoso" with domains "'contoso.onmicrosoft.com'".

Verifying that your script is up to date with the latest changes.

Beginning download of SetupCrossTenantRelationshipForTargetTenant.ps1 and creation of temporary files.

Verifying that a valid location was specified for Azure

A valid Azure location was not specified, please run Get-AzLocation to determine a valid location.

**Comment by Andy-0-Ryan** [comment]
Have you tried "uksouth"?


Location DisplayName
-------- -----------
uksouth  UK South
ukwest   UK West

**Comment by ropow** [comment]
Thanks Andy. Are you being prompted to log into Azure anywhere before Get-AzLocation? If not it's possible that could be the issue.

Before running the script, can you run Connect-AzAccount just to open a connection to Azure to see if that resolves the issue.

Thanks,

Roman

**Comment by ropow** [comment]
Only display name works for AzResourceLocation.

Roman

**Comment by andyonline2k21** [comment]
> Thanks Andy. Are you being prompted to log into Azure anywhere before Get-AzLocation? If not it's possible that could be the issue.

That was it! I had connected to exchange but not azure.
Thank you!

**Comment by Andy-0-Ryan** [comment]
Seems like a good future fix, to ensure we validate the connections when the script is executed.

**Comment by ropow** [comment]
Yes it does.

**Comment by ropow** [comment]
You're welcome!

**Comment by netxgarrett** [comment]
I have this issue now as well:

![image](https://user-images.githubusercontent.com/89261365/130292125-64b20f82-ddfa-484f-97e1-95afbf203744.png)

However, I have done the Connect-AzAccount. Should I be doing the same account that is on my target tenant for the Azure Subscription? I feel as though Microsoft documentation on setting up the resource tenant may be lacking? Unless this is unrelated.

**Comment by ropow** [comment]
You only need a valid Azure subscription when setting up the target tenant. The resource tenant does not use one, per the example in the documentation for setting up the resource tenant:

SetupCrossTenantRelationshipForResourceTenant.ps1 -SourceMailboxMovePublishedScopes "MigScope","MyGroup" -ResourceTenantDomain contoso.onmicrosoft.com -TargetTenantDomain fabrikam.onmicrosoft.com -ApplicationId sdf5e87sa-0753-dd88-ad35-c71a15cs8e44c -TargetTenantId 4sdkfo933-3904-sd93-bf9a-sdi39402834
Exchange setup complete.

Thanks,

Roman

**Comment by netxgarrett** [comment]
Thanks, Roman. Why do you think mine is erroring then? Thanks in advance.

**Comment by ropow** [comment]
Can you send email to ***@***.******@***.***> with the parameters you are running.

Thanks,

Roman

**Comment by netxgarrett** [comment]
Uh, I only got error strings on that. :(

![image](https://user-images.githubusercontent.com/89261365/130296706-55fd060b-a9cc-4173-a8e1-925b75dbb435.png)

**Comment by ropow** [comment]
Can you send email to crosstenantmigrationpreview@service.microsoft.com with the parameters you are running.

Thanks,

Roman
