### ISSUE TITLE
System.Security.Cryptography.SHA256Cng

### ISSUE THREAD

**Issue by andyonline2k21** [microsoft/cross-tenant#72]
Unfortunately hit another error:
```
Line |
 208 |          $azureADAccount = Connect-AzureAD
     |                            ~~~~~~~~~~~~~~~
     | One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type
     | 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

This is using powershell 7, and the latest module versions for Az.

**Comment by ropow** [comment]
Andy,

At this time our scripts are not compatible with PS 7.

Thanks,

Roman


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
From: andyonline2k21 ***@***.***>
Sent: Tuesday, July 27, 2021 1:07:21 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] System.Security.Cryptography.SHA256Cng (#72)


Unfortunately hit another error:

Line |
 208 |          $azureADAccount = Connect-AzureAD
     |                            ~~~~~~~~~~~~~~~
     | One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type
     | 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.


This is using powershell 7, and the latest module versions for Az.

**Comment by andyonline2k21** [comment]
I see- i was using 7 because the AZ module is listed as a requirement and 7 is the recommended version on the documentation page.
What version would you recommend for the required modules?

**Comment by ropow** [comment]
PS 5.1 works just fine with the script and AZ modules. I will be updating the scripts for PS 7 before we release Cross Tenant as GA.

Roman


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by andyonline2k21** [comment]
Thank you-
Thats help me progress somewhat.
My latest issue is the following:

```
WARNING: TenantId '645473a2-62c5-4bab-8a6d-837c0d96587c' contains more than one active subscription. First one will be
selected for further use. To select another subscription, use Set-AzContext.
Setting up key vault in the destination.onmicrosoft.com tenant
Main : Subscription with id 645473a2-62c5-4bab-8a6d-837c0d96587c was not found.
At C:\Windows\system32\SetupCrossTenantRelationshipForTargetTenant.ps1:838 char:1
+ Main
+ ~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Main
```
