### ISSUE TITLE
Resource group already in use

### ISSUE THREAD

**Issue by andyonline2k21** [microsoft/cross-tenant#73]
I've made some progress with this today, however then i hit the following snag.
It looks like the script is trying to create a group twice?
The newly created resource group is empty.

```
Resource Group Cross-TenantMoves2 successfully created
New-AzKeyVault : The vault name 'Cross-TenantMovesVault2' is already in use. Vault names are globaly unique so it is
possible that the name is already taken. If you are sure that the vault name was not taken then it is possible that a
vault with the same name was recently deleted but not purged after being placed in a recoverable state. If the vault
is in a recoverable state then the vault will need to be purged before reusing the name. For more information on soft
delete and purging a vault follow this link https://go.microsoft.com/fwlink/?linkid=2147740.
At C:\Windows\system32\SetupCrossTenantRelationshipForTargetTenant.ps1:364 char:15
+ ...       $kv = New-AzKeyVault -Name $kvName -Location $arLocation -Resou ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzKeyVault], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.NewAzureKeyVault
```

**Comment by ropow** [comment]
You closed out the other case so I am assuming you got past the issue with the subscription ID?

As far as this error, KeyVault names need to be unique globally, so in this case someone else is already using this KeyVault name and you will need to use a different one.

Thanks,

Roman


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
From: andyonline2k21 ***@***.***>
Sent: Tuesday, July 27, 2021 11:51:19 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] Resource group already in use (#73)


I've made some progress with this today, however then i hit the following snag.
It looks like the script is trying to create a group twice?

Resource Group Cross-TenantMoves2 successfully created
New-AzKeyVault : The vault name 'Cross-TenantMovesVault2' is already in use. Vault names are globaly unique so it is
possible that the name is already taken. If you are sure that the vault name was not taken then it is possible that a
vault with the same name was recently deleted but not purged after being placed in a recoverable state. If the vault
is in a recoverable state then the vault will need to be purged before reusing the name. For more information on soft
delete and purging a vault follow this link https://go.microsoft.com/fwlink/?linkid=2147740.
At C:\Windows\system32\SetupCrossTenantRelationshipForTargetTenant.ps1:364 char:15
+ ...       $kv = New-AzKeyVault -Name $kvName -Location $arLocation -Resou ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzKeyVault], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.NewAzureKeyVault

**Comment by andyonline2k21** [comment]
Yes, i did thanks.
I got further after changing the name on the resource group, but hit a new error.

```
Resource Group ATLPTenantMoves successfully created
KeyVault ATLPMovesVault successfully created
Exchange app given access to KeyVault ATLPMovesVault
Self signed certificate requested in key vault - ATLPMovesVault. Certificate name - 59TenantFriendingAppSecret
Certificate 59TenantFriendingAppSecret successfully created
C:\Windows\system32\SetupCrossTenantRelationshipForTargetTenant.ps1 : You cannot call a method on a null-valued
expression.
At line:1 char:1
+ .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDoma ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [SetupCrossTenan...argetTenant.ps1], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,SetupCrossTenantRelationshipForTargetTenant.ps1


```

**Comment by ropow** [comment]
Please rerun the script with the exact same parameters (don't delete the Resource Group/Key Vault that was originally created). This is a timeout on the Azure side and rerunning the script will get you past this.

Roman


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by andyonline2k21** [comment]
OK- I've tried 3 times, same error each time.

**Comment by ropow** [comment]
Are you using -UseAppAndCertGeneratedForSendingInvitation in your parameters? If not can you please run with that as well.

Roman


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by andyonline2k21** [comment]
Yes, the same error occurs

**Comment by ropow** [comment]
Go ahead and try running the script without that parameter then. Unfortunately, this isn't a script related issue and is specific to Azure.

If that doesn't work we can try a modified script with longer timeouts.

Thanks,

Roman


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by andyonline2k21** [comment]
> If that doesn't work we can try a modified script with longer timeouts.

Sounds good. How do I increase the timeouts?

**Comment by ropow** [comment]
Modify line 443 to any timeout you want, I would start with 60 seconds on the sleep.

Modify line 792 to else {Main}


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by andyonline2k21** [comment]
Thanks,
That got me past that error, and on to the next one.
