### ISSUE TITLE
AADSTS90002: Tenant 'token' not found.

### ISSUE THREAD

**Issue by 1trevor** [microsoft/cross-tenant#78]
I receive the following error when running SetupCrossTenantRelationshipForTargetTenant.ps1:

> "AADSTS90002: Tenant 'token' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator."

The error appears to occur when line 607 is executed inside the Get-AccessTokenWithUserPrompt function:

`return $authContext.AcquireTokenAsync($resourceUri, $FIRSTPARTY_POWERSHELL_CLIENTID, $FIRSTPARTY_POWERSHELL_CLIENT_REDIRECT_URI, $platformParams).GetAwaiter().GetResult()`

A fiddler trace shows that the script is attempting to use this URL to acquire the token:

> https://login.microsoftonline.com/token/oauth2/authorize...

That URL appears incorrect. Instead of "token" it should have the target tenant domain/ID or "common"

Note that the Get-AccessTokenWithUserPrompt function has a parameter called authContextTenant that contains the target tenant domain name, but it never actually gets used in the function, which appears to be related to the issue.

**Comment by ropow** [comment]
Thanks Trevor, I will look into fixing this.

**Comment by 1trevor** [comment]
@ropow - I'm still having this issue. I can't make the script work unless I change line 601 to the following:
`$authority = "https://login.microsoftonline.com/common/oauth2/$authContextTenant"`
Could this be an issue with the version of Microsoft.IdentityModel.Clients.ActiveDirectory on my system? I have tried switching to different versions, but it doesn't help.

**Comment by ropow** [comment]
Trevor,

Have you tried just rerunning the script from scratch? This was the solution for the last user who reported this and everything worked fine for him.

Also, when you say you change line 601, that script runs with no issues?

Thanks,

Roman
