### ISSUE TITLE
Cannot validate argument on parameter 'Location'

### ISSUE THREAD

**Issue by snorkmitzumi** [microsoft/cross-tenant#80]
When running .\SetupCrossTenantRelationshipForTargetTenant.ps1 always getting the following error:
`SetupCrossTenantRelationshipForTargetTenant.ps1 : Cannot validate argument on parameter 'Location'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:1 char:1
+ .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDoma ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [SetupCrossTenan...argetTenant.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,SetupCrossTenantRelationshipForTargetTenant.ps1`

Location is specified, Vault is created but nothing happens afterwards

**Comment by duffman36** [comment]
It seems and I am very very far from familiar with powershell, but it looks like theyu use $AzureResourceLocation as a variable and then in this function
function Create-KeyVaultAndGenerateCertificate([string]$targetTenant, `
                                               [string]$resourceTenantDomain, `
                                               [string]$resourceGrpName, `
                                               [string]$kvName, `
                                               [string]$arLocation, `
                                               [string]$certName, `
                                               [string]$certSubj, `
                                               [string]$exoAppObjectId, `
                                               [bool]$retrieveCertPrivateKey, `
                                               [string]$auditStorageAcntRG, `
                                               [string]$auditStorageAcntName, `
                                               [string]$auditStorageAcntLocation, `
                                               [string]$auditStorageAcntSKU, `
                                               [guid]$existingApplicationId) {

they change to $arLocation. I am not sure if this is the issue but I am having the same problem as you are.

**Comment by ropow** [comment]
Good morning. The reason you are hitting the Location error is you also need to specify KeyVaultAuditStorageAccountLocation.

Thanks,

Roman
