### ISSUE TITLE
Hardcoded organisation name

### ISSUE THREAD

**Issue by Videsh-Lingabavan** [microsoft/cross-tenant#82]
Line 801 has this:

    New-OrganizationRelationship -DomainNames contoso.onmicrosoft.com -Name Contoso -WhatIf -ErrorAction Stop

Contoso is hardcoded, I'm sure this should be a variable

**Comment by Andy-0-Ryan** [comment]
This is within a try / catch statement to validate if the org has enabled customization, it does not actually execute (note the -whatif)
