### ISSUE TITLE
Process stop with no error or feedback

### ISSUE THREAD

**Issue by thom4966** [microsoft/cross-tenant#86]
I'm curious on the length of time to wait or if there are errors not being reported/captured, but after running the TargetTenant script, the process stops. Is there a way to log the scripts to see where this may be hung up?

Where it stops:
Beginning verification steps.

Verifying ability to create a new organization relationship in the tenant.
What if: Creating organization relationship "Contoso" with domains "'contoso.onmicrosoft.com'".

Verifying that your script is up to date with the latest changes.

Beginning download of SetupCrossTenantRelationshipForTargetTenant.ps1 and creation of temporary files.

Verifying that a valid location was specified for Azure

You are using the latest version of the script. Removing temporary files and proceeding with setup.

**Comment by ropow** [comment]
As I've gotten no response. I'm closing this issue out. Feel free to send email to crosstenantmigrationpreview@service.microsoft.com if you are continuing to have issues.

Thanks,

Roman
