### ISSUE TITLE
Line 329 : Assembly with same name is already loaded

### ISSUE THREAD

**Issue by beejayvee** [microsoft/cross-tenant#88]
I'm receiving when executing SetupCrossTenantRelationshipForTargetTenant.ps1:

Line |
 329 |      $desiredAzureModules.Keys | Import-Module -verbose:$false | Out-N …
        |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        | Assembly with same name is already loaded

**Comment by ropow** [comment]
As I've gotten no response. I'm closing this issue out. Feel free to send email to crosstenantmigrationpreview@service.microsoft.com if you are continuing to have issues.

Thanks,

Roman
