### ISSUE TITLE
Error in the new procedure

### ISSUE THREAD

**Issue by yuryrodrigues** [microsoft/cross-tenant#89]
Hey guys,

The current procedure does not work for me. I can't migrate any mailboxes from source to destination.

In the other Issue I received the new procedure (documentation 2.0). But it does not work. I get the error below:

------->

PS C:\WINDOWS\system32> Test-MigrationServerAvailability -Endpoint "amb-to-n1" -TestMailbox "pedro@ambienteescolar02.onmicrosoft.com"

RunspaceId      : db613b45-d96c-4376-a1f3-b092bb1548df
Result          : Failed
                  couldn't be found on 'CP2PR80A001DC03.LAMPR80A001.prod.outlook.com'.
SupportsCutover : False
ErrorDetail     : Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException: Could not perform operation because object  'pedro@ambienteescolar02.onmicrosoft.com' em could not be found on                   'CP2PR80A001DC03.LAMPR80A001.prod.outlook.com'.
                     at
                  Microsoft.Exchange.Configuration.Tasks.DataAccessTask`1.GetDataObject[TObject](IIdentityParameter
                  id, IConfigDataProvider session, ObjectId rootID, OptionalIdentityData optionalData, Func`2
                  notFoundError, Func`2 multipleFoundError, ExchangeErrorCategory errorCategory)
                     at Microsoft.Exchange.Configuration.Tasks.RecipientTaskHelper.ResolveDataObject[TDataObject](IConf
                  igDataProvider dataSession, IConfigDataProvider globalCatalogSession, Boolean viewEntireForest,
                  IIdentityParameter identity, ObjectId rootId, OptionalIdentityData optionalData, String
                  domainController, CategorizedGetDataObjectDelegate getDataObjectHandler, TaskVerboseLoggingDelegate
                  logHandler, ErrorLoggerDelegate errorHandler)
                     at Microsoft.Exchange.MailboxReplicationService.RequestTaskHelper.ResolveADRecipient[T](IRecipient
                  Session dataSession, IRecipientSession globalCatalogSession, ADServerSettings serverSettings,
                  IIdentityParameter identity, OptionalIdentityData optionalData, String domainController,
                  CategorizedGetDataObjectDelegate getDataObjectHandler, TaskVerboseLoggingDelegate logVerbose,
                  ErrorLoggerDelegate writeError, Boolean checkScopes)
                     at Microsoft.Exchange.Management.Migration.MigrationService.Endpoint.TestMigrationServerAvailabili
                  ty.InternalProcessEndpoint(Boolean fromAutoDiscover)
TestedEndpoint  :
IsValid         : True
Identity        :
ObjectState     : New

------->

If I specify an account that is not in the mailbox-enabled security group on the source, I get this error:

Message         : You can't use the domain  because it's not an accepted domain for your organization.

If I specify an account that is in the mailbox-enabled security group on the source, I get this error:

ErrorDetail     : Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException: Could not perform operation because object  'pedro@ambienteescolar02.onmicrosoft.com' em could not be found on                   'CP2PR80A001DC03.LAMPR80A001.prod.outlook.com'.

Is there a solution for this error?
![image](https://user-images.githubusercontent.com/7195945/138454598-d70e6517-8d89-4357-9692-8195e5bb88d7.png)
[Cross-tenant.mailbox.migration.preview.v2.pdf](https://github.com/microsoft/cross-tenant/files/7397140/Cross-tenant.mailbox.migration.preview.v2.pdf)

**Comment by ropow** [comment]
Yury,

As I've gotten no response. I'm closing this issue out. Feel free to send email to crosstenantmigrationpreview@service.microsoft.com if you are continuing to have issues.

Thanks,

Roman
