### ISSUE TITLE
Errors verifying AAD application

### ISSUE THREAD

**Issue by richard-optek** [microsoft/cross-tenant#94]
I was able to follow most of the steps through the Cross-Tenant mailbox migration walkthrough and "The new procedure doesn't work for me #90".

I'm stuck with "App [app_id] does not have [Mailbox.Migration] permission on Exchange setup or the permission is not consented by an Administrator.  I have tried removing the permission, adding it back and accepting it in both tenants, this did not change the error.

What step(s) am/are I missing to get this across the finish line?

![aad app fail](https://user-images.githubusercontent.com/98972230/152391238-6e55f587-2e28-4933-860e-846bd3ff02b1.png)

**Comment by ropow** [comment]
Richard,

Are you receiving this error when running the verification script against the target or source tenant?

Thanks,

Roman

From: richard-optek ***@***.***>
Sent: Thursday, February 3, 2022 9:01 AM
To: microsoft/cross-tenant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/cross-tenant] Errors verifying AAD application (Issue #94)


I was able to follow most of the steps through the Cross-Tenant mailbox migration walkthrough and "The new procedure doesn't work for me #90<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcross-tenant%2Fissues%2F90&data=04%7C01%7CRoman.Powell%40microsoft.com%7C29aaf79f5f35465fd60c08d9e736c2cb%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637795045154072383%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7KVJkVT8pD6JTjWfcygZGUO1ZIjEwM8mGJzRRr068Ks%3D&reserved=0>".

I'm stuck with "App [app_id] does not have [Mailbox.Migration] permission on Exchange setup or the permission is not consented by an Administrator. I have tried removing the permission, adding it back and accepting it in both tenants, this did not change the error.

What step(s) am/are I missing to get this across the finish line?

[aad app fail]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F98972230%2F152391238-6e55f587-2e28-4933-860e-846bd3ff02b1.png&data=04%7C01%7CRoman.Powell%40microsoft.com%7C29aaf79f5f35465fd60c08d9e736c2cb%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637795045154072383%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NFSQbBtezJ1xrPQMYoOb1Ik%2BO7ZfkJamBSOtFKD5t5c%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fcross-tenant%2Fissues%2F94&data=04%7C01%7CRoman.Powell%40microsoft.com%7C29aaf79f5f35465fd60c08d9e736c2cb%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637795045154072383%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NvUrO0HOrCFtI4xI09NrooB0qzQr8D3SIbdWJEAW8TU%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPUHY6EQKCBIYK5V43BBKBDUZKYE5ANCNFSM5NPPSPHA&data=04%7C01%7CRoman.Powell%40microsoft.com%7C29aaf79f5f35465fd60c08d9e736c2cb%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637795045154122384%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LM3c479XdxrusXNhhUN%2BUobkioi2lpkX2k3a0PEYgOY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CRoman.Powell%40microsoft.com%7C29aaf79f5f35465fd60c08d9e736c2cb%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637795045154122384%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KFqunOZmUj6abmKRowf%2FBCyek%2Bkzh0SAJgS5kwsgVV4%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CRoman.Powell%40microsoft.com%7C29aaf79f5f35465fd60c08d9e736c2cb%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637795045154122384%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=C4o931Nzj8dVa8Xko%2FilKit7ssX1N40U2hZqdHVqnqI%3D&reserved=0>.

**Comment by richard-optek** [comment]
Hi Roman,

I’m running this in the Target with the partner info pointing at the Source Tenant.

$SourceTenantId=" " #Source Tenant
$AADApplicationId=" " #Cross tenant migration app
$SourceTenantDomain=" " #Source Domain
$report = .\VerifySetup.ps1 -PartnerTenantId $SourceTenantId -ApplicationId $AADApplicationId  -PartnerTenantDomain $SourceTenantDomain -Verbose

Should I be running these on the Target domain instead of Source?

Richard

**Comment by ropow** [comment]
Richard,

That's the correct properties required. Can you verify that this is what you see on the enterprise application in Azure and can you share the URL you used to consent to the application in the source?

Thanks,

Roman

***@***.***

**Comment by richard-optek** [comment]
The Application URL is https://login.microsoftonline.com/longlakeinsurance.onmicrosoft.com/adminconsent?client_id=[42368940-fefc-4177-9a76-b621761a3f62]&redirect_uri=https://office.com

In the enterprise app overview from the source:
![enterprise app from source](https://user-images.githubusercontent.com/98972230/152407781-cd09f7b0-3873-41e9-ba47-4c834d765cab.png)

And same app from the target:
![enterprise app from target](https://user-images.githubusercontent.com/98972230/152407867-26a71633-76bb-4a05-98ad-23e880856537.png)

**Comment by ropow** [comment]
Can you verify what is shown under Security > Permissions in both the target and source tenants?

Thanks,

Roman

**Comment by richard-optek** [comment]
I got from Source:
![source security](https://user-images.githubusercontent.com/98972230/152411543-e8d5819b-0728-47fd-b418-efcff30d7dd0.png)

and Target:
![Target Security](https://user-images.githubusercontent.com/98972230/152411592-f09f2033-bfa4-44e3-97b1-e5b22a33be91.png)

**Comment by ropow** [comment]
That looks like  just what is available.

Go to Enterprise Applications > Your application > Security > Permissions and see what is there, it should look like the screenshot I previously shared.

Thanks,

Roman

**Comment by richard-optek** [comment]
Sorry, I didn't see a screenshot from you before.  The screenshots I grabbed were from the Enterprise Applications > App > Security > Permissions and under Admin Consent.  When I was having issues originally I tried enabling all the API permissions to make sure there wasn't something missed.

**Comment by ropow** [comment]
Richard,

Can you share your source and target tenants so I can look at other pieces of the setup. If you don't want them posted on GitHub, please email us at ***@***.******@***.***>

Thanks,

Roman

**Comment by richard-optek** [comment]
Target tenant: redacted
Target ID: redacted

Source tenant: redacted
Source ID: redacted

**Comment by ropow** [comment]
Sorry that GitHub blocks out the email when replying via mail, here is the correct address.

crosstenantmigrationpreview@service.microsoft.com

On that note, I do not see anything wrong with your setup. The only thing that I'm wondering if it caused a problem is the URL you consented too:

https://login.microsoftonline.com/longlakeinsurance.onmicrosoft.com/adminconsent?client_id=[42368940-fefc-4177-9a76-b621761a3f62]&redirect_uri=https://office.com

There shouldn't be [] around the application ID. Can you delete the Enterprise Application in the source tenant, fix the URL and try again?

Thanks,

Roman

**Comment by richard-optek** [comment]
Sorry, I did remove those in production. I can remove from the source and reconnect it.

**Comment by ropow** [comment]
Ah if you did so in production then no need to remove the application in the source and try again. Do you want to setup a meeting so we can go over things together.

**Comment by richard-optek** [comment]
That would be great, I'm out of the office for the rest of today and doing an onsite discovery tomorrow.  Would some time Monday work for you?

**Comment by ropow** [comment]
Yes that's fine. Please email me at ***@***.******@***.***> and we'll get some time setup.

Roman

**Comment by ropow** [comment]
Reposting here so that the email isn't cutoff again:

Yes that's fine. Please email me at ropow@microsoft.com and we'll get some time setup.

Roman

**Comment by chieclamuadong072** [comment]
The same issues... Can you help me check it?
