### ISSUE TITLE
The source tenant does not authorize mailbox for migration

### ISSUE THREAD

**Issue by juanneres** [microsoft/cross-tenant#96]
Hello.
I'm trying to use this feature following the [official documentation](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide) and a tutorial on Youtube, but when I run the test command "Test-MigrationServerAvailability -EndPoint "[the name of your migration endpoint]" -TestMailbox "[Primary SMTP of MailUser object in target tenant]"" (Replacing the values, obviously) returns that the source tenant does not authorize the mailbox migration.

How can I enable this migration?

I already repeated the step by step several times, including using different names in the API, Endpoint, etc, so that there was no conflict.

I correctly collected the ExchangeGUID and LegacyExchangeDN values ​​from the MailBox in the source and assigned to the MailUser in the target.

I also enabled some parameters with Set-OrganizationRelationship, but without success.

Below is the complete error:

> Result          : Failed
> Message         : The connection to the server 'outlook.office365.com' could not be completed.
> SupportsCutover : False
> ErrorDetail     : Microsoft.Exchange.Migration.MigrationServerConnectionFailedException: Não foi possível concluir a conexão ao servidor
>                   'outlook.office365.com'. ---> Microsoft.Exchange.MailboxReplicationService.MRSRemotePermanentException: The source tenant
>                   'adfc66f7-9f68-48d1-8337-7b77a2b946e7' does not authorize mailbox 'c14b6cc0-9172-4651-a9c1-71c0f97d43e9' for migration.
>                   Please ensure the migration scope is setup correctly on the source tenant and scope identifier is set in organization
>                   relationship.
>                      at Microsoft.Exchange.MailboxReplicationService.MailboxReplicationServiceFault.ReconstructAndThrow(String serverName,
>                   VersionInformation serverVersion)
>                      at Microsoft.Exchange.Connections.Common.WcfClientWithFaultHandling`2.<>c__DisplayClass4_0.<CallService>b__0()
>                      at Microsoft.Exchange.Net.WcfClientBase`1.CallService(Action serviceCall, String context)
>                      at Microsoft.Exchange.Connections.Common.WcfClientWithFaultHandling`2.CallService(Action serviceCall, String context)
>                      at Microsoft.Exchange.MailboxReplicationService.WcfClientWithVersion`2.CallService(Action serviceCall, String context)
>                      at Microsoft.Exchange.MailboxReplicationService.MailboxReplicationServiceClient.GetMailboxInformation(RequestJobBase
>                   requestJob, Guid primaryMailboxGuid, Guid physicalMailboxGuid, TenantPartitionHint partitionHint, ADObjectId
>                   targetMdbAdObjectId, String targetMdbName, String remoteHostName, String remoteOrgName, Guid requesterOrgId, String
>                   remoteDCName, NetworkCredential cred, MailboxConnectFlags mailboxConnectFlags)
>                      at Microsoft.Exchange.Migration.MigrationExchangeProxyRpcClient.GetMailboxInformation(TransactionalRequestJob
>                   requestJob, Guid primaryMailboxGuid, Guid physicalMailboxGuid, TenantPartitionHint partitionHint, ADObjectId
>                   targetMdbAdObjectId, String targetMdbName, String remoteHostName, String remoteOrgName, Guid requesterOrgId, String
>                   remoteDCName, NetworkCredential cred, LocalizedException& error)
>                      --- End of inner exception stack trace ---
>                      at Microsoft.Exchange.Migration.MigrationEndpointVerifier.GetMailboxInformation(String remoteServer,
>                   TransactionalRequestJob requestJob, Guid primaryMailboxGuid, Guid physicalMailboxGuid, String sourceTenantName, Guid
>                   targetTenantId, TenantPartitionHint targetTenantPartitionHint, ADObjectId targetMdbId, NetworkCredential appCred)
>                      at Microsoft.Exchange.Management.Migration.MigrationService.Endpoint.TestMigrationServerAvailability.InternalProcessCro
>                   ssTenantScenario()
>                      at Microsoft.Exchange.Management.Migration.MigrationService.Endpoint.TestMigrationServerAvailability.InternalProcessEnd
>                   point(Boolean fromAutoDiscover)
> TestedEndpoint  :
> IsValid         : True
> Identity        :
> ObjectState     : New

**Comment by ropow** [comment]
Good evening, Juan.

Did you create the mail-enabled security group in the source tenant and add the mailbox you are testing, to that group?

https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide#prerequisites-for-source-and-target-tenants

Thanks,

Roman

**Comment by juanneres** [comment]
> It worked. Thanks!
