### ISSUE TITLE
Target delivery domain not found

### ISSUE THREAD

**Issue by juanneres** [microsoft/cross-tenant#97]
Hello.
I'm creating the Migration Batch, but when I need to insert the "Target delivery domain" it doesn't accept mine even though it's correct.
Returns the error "Target delivery domain not found".

The domain is on the list of accepted domains and is the tenant's primary domain.

How can I resolve this?

Thanks.

**Comment by ropow** [comment]
Good afternoon, Juan. Can you open a support case to get assistance with these issues?

Thanks,

Roman

**Comment by juanneres** [comment]
I solved it by creating a MigrationBatch via PowerShell

`New-MigrationBatch -Name T2Tbatch -SourceEndpoint Endpoint_name_here -CSVData([System.IO.File]::ReadAllBytes('path_csv_file_here')) -Autostart -TargetDeliveryDomain target_domain_here`
