### ISSUE TITLE
Add the ExchangeGuid and LegacyExchangeDN

### ISSUE THREAD

**Issue by juanneres** [microsoft/cross-tenant#98]
Is there any way to add the ExchangeGuid and LegacyExchangeDN(X500) values ​​through a script using a CSV?

**Comment by ropow** [comment]
Juan,

You could write a script to pull the values from a CSV file and use Set-MailUser.

If you look in the FAQ of the documentation for Cross-Tenant migration there are examples there that will copy all attributes from the source and place them in an XML file, that can then be used to create the mail users with the needed attributes.

Roman

**Comment by juanneres** [comment]
> 
That example is for an on-premise target.

I'm migrating Exchange Online to Exchange Online.

**Comment by ropow** [comment]
That example works for on-premise or cloud only. There are two lines in there that you don't run (the one
s for on-prem) if cloud only.
